import { Geist, Geist_Mono } from 'next/font/google';
import { init } from 'next/dist/compiled/webpack/webpack';
import { initialize } from 'next/dist/server/lib/render-server';

import { IssueProvider } from '@/components/providers/issue-provider';
import { storage } from '@/lib/storage';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  const initialIssues = storage.getAll();

  return (
    <html lang="en">
      <body>
        <IssueProvider initialIssues={initialIssues}>
          {children}
        </IssueProvider>
      </body>
    </html>
  );
}
